#############################################################################
# Generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#  Apr 16, 2023 01:43:04 AM CEST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x536+602+255
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::style configure PNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure PNotebook -foreground $vTcl(actual_gui_fg)
    ttk::style configure PNotebook -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure PC.TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure PC.TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure PC.TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure PC.TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map PC.TNotebook.Tab -background [list selected $vTcl(actual_gui_bg) active $vTcl(tabbg1) !active $vTcl(tabbg2)]
    ttk::style map PC.TNotebook.Tab -foreground [list selected $vTcl(actual_gui_fg) active $vTcl(tabfg1) !active $vTcl(tabfg2)]
    ttk::style layout PC.TNotebook.Tab {
                    Notebook.tab -children {
                        Notebook.padding -side top -children {
                           t Notebook.focus -side top -children {
                                Notebook.text -side right
                                Notebook.image -side left
                            }
                        }

                    }
               }
    vTcl::widgets::ttk::pnotebook::createCmd "$top.pNo47" \
        -width 300 -height 200 -style "PC.TNotebook" -style PC.TNotebook 
    vTcl:DefineAlias "$top.pNo47" "PNotebook1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $top.pNo47 configure -style "PC.TNotebook"
    bind $top.pNo47 <Button-1> {
        _button_press
    }
    bind $top.pNo47 <ButtonRelease-1> {
        _button_release
    }
    bind $top.pNo47 <Motion> {
        _mouse_over
    }
    ttk::style configure Frame -background $vTcl(actual_gui_bg)
    ttk::style configure Frame -foreground $vTcl(actual_gui_fg)
    ttk::style configure Frame -font "$vTcl(actual_gui_font_dft_desc)"
    frame "$top.pNo47.t0" \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.pNo47.t0" "PNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $top.pNo47 add $top.pNo47.t0 \
        -padding 0 -sticky nsew -state normal -text "Projet" -image image6 \
        -compound left -underline -1 
    set site_4_0  $top.pNo47.t0
    ttk::style configure PNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure PNotebook -foreground $vTcl(actual_gui_fg)
    ttk::style configure PNotebook -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure PC.TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure PC.TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure PC.TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure PC.TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map PC.TNotebook.Tab -background [list selected $vTcl(actual_gui_bg) active $vTcl(tabbg1) !active $vTcl(tabbg2)]
    ttk::style map PC.TNotebook.Tab -foreground [list selected $vTcl(actual_gui_fg) active $vTcl(tabfg1) !active $vTcl(tabfg2)]
    ttk::style layout PC.TNotebook.Tab {
                    Notebook.tab -children {
                        Notebook.padding -side top -children {
                           t Notebook.focus -side top -children {
                                Notebook.text -side right
                                Notebook.image -side left
                            }
                        }

                    }
               }
    vTcl::widgets::ttk::pnotebook::createCmd "$site_4_0.pNo48" \
        -width 300 -height 200 -style "PC.TNotebook" -style PC.TNotebook 
    vTcl:DefineAlias "$site_4_0.pNo48" "PNotebook2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $site_4_0.pNo48 configure -style "PC.TNotebook"
    bind $site_4_0.pNo48 <Button-1> {
        _button_press
    }
    bind $site_4_0.pNo48 <ButtonRelease-1> {
        _button_release
    }
    bind $site_4_0.pNo48 <Motion> {
        _mouse_over
    }
    ttk::style configure Frame -background $vTcl(actual_gui_bg)
    ttk::style configure Frame -foreground $vTcl(actual_gui_fg)
    ttk::style configure Frame -font "$vTcl(actual_gui_font_dft_desc)"
    frame "$site_4_0.pNo48.t0" \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_4_0.pNo48.t0" "PNotebook2_t1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $site_4_0.pNo48 add $site_4_0.pNo48.t0 \
        -padding 0 -sticky nsew -state normal -text "Gantt" -image image6 \
        -compound left -underline -1 
    set site_6_0  $site_4_0.pNo48.t0
    ttk::style configure TPanedwindow -background $vTcl(actual_gui_bg)
    ttk::style configure TPanedwindow -foreground $vTcl(actual_gui_fg)
    ttk::style configure TPanedwindow -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TPanedwindow -background $vTcl(actual_gui_bg)
    ttk::style configure TPanedwindow.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TPanedwindow.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TPanedwindow.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::panedwindow "$site_6_0.tPa47" \
        -orient horizontal 
    vTcl:DefineAlias "$site_6_0.tPa47" "TPanedwindow1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe "$site_6_0.tPa47.p1" \
        -text "Tasks" -width 75 -height 200 
    vTcl:DefineAlias "$site_6_0.tPa47.p1" "TPanedwindow1_p1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_8_0 $site_6_0.tPa47.p1
    $site_6_0.tPa47 add $site_6_0.tPa47.p1 
    $site_6_0.tPa47 pane $site_6_0.tPa47.p1 -weight 0
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe "$site_6_0.tPa47.p2" \
        -text "Gantt" -width 154 -height 200 
    vTcl:DefineAlias "$site_6_0.tPa47.p2" "TPanedwindow1_p2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_8_1 $site_6_0.tPa47.p2
    $site_6_0.tPa47 add $site_6_0.tPa47.p2 
    $site_6_0.tPa47 pane $site_6_0.tPa47.p2 -weight 0
$site_8_0 configure -width 75
    ttk::style configure Scale -background $vTcl(actual_gui_bg)
    ttk::style configure Scale -foreground $vTcl(actual_gui_fg)
    ttk::style configure Scale -font "$vTcl(actual_gui_font_dft_desc)"
    scale "$site_6_0.sca49" \
        -activebackground $vTcl(analog_color_m) \
        -background $vTcl(actual_gui_bg) -bigincrement 0.0 \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) -from 0.0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -length 376 -resolution 1.0 -tickinterval 0.0 -to 100.0 \
        -troughcolor #d9d9d9 
    vTcl:DefineAlias "$site_6_0.sca49" "Scale1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_6_0.tPa47 \
        -in $site_6_0 -x 0 -y 0 -width 0 -relwidth 0.932 -height 0 \
        -relheight 1 -anchor nw -bordermode ignore 
    place $site_6_0.sca49 \
        -in $site_6_0 -x 0 -relx 0.929 -y 0 -rely 0.021 -width 45 -relwidth 0 \
        -height 0 -relheight 0.944 -anchor nw -bordermode ignore 
    ttk::style configure Frame -background $vTcl(actual_gui_bg)
    ttk::style configure Frame -foreground $vTcl(actual_gui_fg)
    ttk::style configure Frame -font "$vTcl(actual_gui_font_dft_desc)"
    frame "$site_4_0.pNo48.t1" \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_4_0.pNo48.t1" "PNotebook2_t2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $site_4_0.pNo48 add $site_4_0.pNo48.t1 \
        -padding 0 -sticky nsew -state normal -text "WBS" -image image6 \
        -compound left -underline -1 
    set site_6_1  $site_4_0.pNo48.t1
    ttk::style configure Custom -background $vTcl(actual_gui_bg)
    ttk::style configure Custom -foreground $vTcl(actual_gui_fg)
    ttk::style configure Custom -font "$vTcl(actual_gui_font_dft_desc)"
    vTcl::widgets::ttk::custom::CreateCmd "$site_6_1.cus49" \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$site_6_1.cus49" "Custom1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_6_1.cus49 \
        -in $site_6_1 -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    place $site_4_0.pNo48 \
        -in $site_4_0 -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    ttk::style configure Frame -background $vTcl(actual_gui_bg)
    ttk::style configure Frame -foreground $vTcl(actual_gui_fg)
    ttk::style configure Frame -font "$vTcl(actual_gui_font_dft_desc)"
    frame "$top.pNo47.t1" \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.pNo47.t1" "PNotebook1_t2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $top.pNo47 add $top.pNo47.t1 \
        -padding 0 -sticky nsew -state normal -text "Ressource" -image image6 \
        -compound left -underline -1 
    set site_4_1  $top.pNo47.t1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.pNo47 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

