#############################################################################
# Generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#  Apr 17, 2023 10:43:58 PM CEST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 888x661+365+188
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::style configure PC.TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure PC.TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure PC.TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure PC.TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map PC.TNotebook.Tab -background [list selected $vTcl(actual_gui_bg) active $vTcl(tabbg1) !active $vTcl(tabbg2)]
    ttk::style map PC.TNotebook.Tab -foreground [list selected $vTcl(actual_gui_fg) active $vTcl(tabfg1) !active $vTcl(tabfg2)]
    ttk::style layout PC.TNotebook.Tab {
                    Notebook.tab -children {
                        Notebook.padding -side top -children {
                           t Notebook.focus -side top -children {
                                Notebook.text -side right
                                Notebook.image -side left
                            }
                        }

                    }
               }
    vTcl::widgets::ttk::pnotebook::createCmd "$top.pNo47" \
        -width 300 -height 200 -style "PC.TNotebook" -style PC.TNotebook 
    vTcl:DefineAlias "$top.pNo47" "PNotebook1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $top.pNo47 configure -style "PC.TNotebook"
    bind $top.pNo47 <Button-1> {
        _button_press
    }
    bind $top.pNo47 <ButtonRelease-1> {
        _button_release
    }
    bind $top.pNo47 <Motion> {
        _mouse_over
    }
    frame "$top.pNo47.t0" \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.pNo47.t0" "PNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $top.pNo47 add $top.pNo47.t0 \
        -padding 0 -sticky nsew -state normal -text "Projet" -image image6 \
        -compound left -underline -1 
    set site_4_0  $top.pNo47.t0
    ttk::style configure PC.TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure PC.TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure PC.TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure PC.TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map PC.TNotebook.Tab -background [list selected $vTcl(actual_gui_bg) active $vTcl(tabbg1) !active $vTcl(tabbg2)]
    ttk::style map PC.TNotebook.Tab -foreground [list selected $vTcl(actual_gui_fg) active $vTcl(tabfg1) !active $vTcl(tabfg2)]
    ttk::style layout PC.TNotebook.Tab {
                    Notebook.tab -children {
                        Notebook.padding -side top -children {
                           t Notebook.focus -side top -children {
                                Notebook.text -side right
                                Notebook.image -side left
                            }
                        }

                    }
               }
    vTcl::widgets::ttk::pnotebook::createCmd "$site_4_0.pNo47" \
        -width 300 -height 200 -style "PC.TNotebook" -style PC.TNotebook 
    vTcl:DefineAlias "$site_4_0.pNo47" "PNotebook3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $site_4_0.pNo47 configure -style "PC.TNotebook"
    bind $site_4_0.pNo47 <Button-1> {
        _button_press
    }
    bind $site_4_0.pNo47 <ButtonRelease-1> {
        _button_release
    }
    bind $site_4_0.pNo47 <Motion> {
        _mouse_over
    }
    frame "$site_4_0.pNo47.t0" \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_4_0.pNo47.t0" "PNotebook3_t1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $site_4_0.pNo47 add $site_4_0.pNo47.t0 \
        -padding 0 -sticky nsew -state normal -text "Tasks" -image image6 \
        -compound left -underline -1 
    set site_6_0  $site_4_0.pNo47.t0
    ttk::style configure PC.TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure PC.TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure PC.TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure PC.TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map PC.TNotebook.Tab -background [list selected $vTcl(actual_gui_bg) active $vTcl(tabbg1) !active $vTcl(tabbg2)]
    ttk::style map PC.TNotebook.Tab -foreground [list selected $vTcl(actual_gui_fg) active $vTcl(tabfg1) !active $vTcl(tabfg2)]
    ttk::style layout PC.TNotebook.Tab {
                    Notebook.tab -children {
                        Notebook.padding -side top -children {
                           t Notebook.focus -side top -children {
                                Notebook.text -side right
                                Notebook.image -side left
                            }
                        }

                    }
               }
    vTcl::widgets::ttk::pnotebook::createCmd "$site_6_0.pNo48" \
        -width 300 -height 200 -style "PC.TNotebook" -style PC.TNotebook 
    vTcl:DefineAlias "$site_6_0.pNo48" "PNotebook2_1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $site_6_0.pNo48 configure -style "PC.TNotebook"
    bind $site_6_0.pNo48 <Button-1> {
        _button_press
    }
    bind $site_6_0.pNo48 <ButtonRelease-1> {
        _button_release
    }
    bind $site_6_0.pNo48 <Motion> {
        _mouse_over
    }
    frame "$site_6_0.pNo48.t0" \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_6_0.pNo48.t0" "PNotebook2_t1_1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $site_6_0.pNo48 add $site_6_0.pNo48.t0 \
        -padding 0 -sticky nsew -state normal -text "Gantt" -image image6 \
        -compound left -underline -1 
    set site_8_0  $site_6_0.pNo48.t0
    ttk::style configure TPanedwindow -background $vTcl(actual_gui_bg)
    ttk::style configure TPanedwindow.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TPanedwindow.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TPanedwindow.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::panedwindow "$site_8_0.tPa47" \
        -orient horizontal 
    vTcl:DefineAlias "$site_8_0.tPa47" "TPanedwindow1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe "$site_8_0.tPa47.p1" \
        -text "Pane 1" -width 250 -height 200 
    vTcl:DefineAlias "$site_8_0.tPa47.p1" "TPanedwindow1_p1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_10_0 $site_8_0.tPa47.p1
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd "$site_10_0.scr47" \
        -background $vTcl(actual_gui_bg) -height 15 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$site_10_0.scr47" "Scrolledtreeview1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A

        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 configure -columns "Col1 Col2 Col3 Col4 Col5" -height 4
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 configure -columns {Col1 Col2 Col3 Col4 Col5}
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 heading #0 -text {Tree}
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 heading #0 -anchor center
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 column #0 -width 115
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 column #0 -minwidth 20
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 column #0 -stretch 1
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 column #0 -anchor w
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 heading Col1 -text {Col1}
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 heading Col1 -anchor center
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 column Col1 -width 116
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 column Col1 -minwidth 20
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 column Col1 -stretch 1
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 column Col1 -anchor w
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 heading Col2 -text {Col2}
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 heading Col2 -anchor center
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 column Col2 -width 200
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 column Col2 -minwidth 20
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 column Col2 -stretch 1
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 column Col2 -anchor w
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 heading Col3 -text {Col3}
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 heading Col3 -anchor center
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 column Col3 -width 200
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 column Col3 -minwidth 20
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 column Col3 -stretch 1
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 column Col3 -anchor w
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 heading Col4 -text {Col4}
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 heading Col4 -anchor center
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 column Col4 -width 200
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 column Col4 -minwidth 20
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 column Col4 -stretch 1
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 column Col4 -anchor w
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 heading Col5 -text {Col5}
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 heading Col5 -anchor center
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 column Col5 -width 200
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 column Col5 -minwidth 20
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 column Col5 -stretch 1
        $base.pNo47.t0.pNo47.t0.pNo48.t0.tPa47.p1.scr47.01 column Col5 -anchor w
    place $site_10_0.scr47 \
        -in $site_10_0 -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    $site_8_0.tPa47 add $site_8_0.tPa47.p1 
    $site_8_0.tPa47 pane $site_8_0.tPa47.p1 -weight 0
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe "$site_8_0.tPa47.p2" \
        -text "Pane 2" -width 125 -height 200 
    vTcl:DefineAlias "$site_8_0.tPa47.p2" "TPanedwindow1_p2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_10_1 $site_8_0.tPa47.p2
    vTcl::widgets::ttk::scrolledwindow::CreateCmd "$site_10_1.scr48" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 100 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 150 
    vTcl:DefineAlias "$site_10_1.scr48" "Scrolledwindow1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A

    $site_10_1.scr48.01 configure -background white \
        -borderwidth 2 \
        -height 75 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -relief groove \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 125
    place $site_10_1.scr48 \
        -in $site_10_1 -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    $site_8_0.tPa47 add $site_8_0.tPa47.p2 
    $site_8_0.tPa47 pane $site_8_0.tPa47.p2 -weight 0
$site_10_0 configure -width 250
    place $site_8_0.tPa47 \
        -in $site_8_0 -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    frame "$site_6_0.pNo48.t1" \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_6_0.pNo48.t1" "PNotebook2_t2_1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $site_6_0.pNo48 add $site_6_0.pNo48.t1 \
        -padding 0 -sticky nsew -state normal -text "WBS" -image image6 \
        -compound left -underline -1 
    set site_8_1  $site_6_0.pNo48.t1
    vTcl::widgets::ttk::custom::CreateCmd "$site_8_1.cus49" \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$site_8_1.cus49" "Custom1_1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_8_1.cus49 \
        -in $site_8_1 -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    place $site_6_0.pNo48 \
        -in $site_6_0 -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    frame "$site_4_0.pNo47.t1" \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_4_0.pNo47.t1" "PNotebook3_t2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $site_4_0.pNo47 add $site_4_0.pNo47.t1 \
        -padding 0 -sticky nsew -state normal -text "Ressources" \
        -image image6 -compound left -underline -1 
    set site_6_1  $site_4_0.pNo47.t1
    place $site_4_0.pNo47 \
        -in $site_4_0 -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.pNo47 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

